#!/usr/bin/env bash
set -euo pipefail

echo "Linking .zshrc"
ln -sf "$HOME/.config/zsh/.zshrc" "$HOME/.zshrc"
ln -sf "$HOME/.config/zsh/general.zsh" "$HOME/.oh-my-zsh/custom"
ln -sf "$HOME/.config/zsh/.zprofile" "$HOME/.zprofile"

echo "Linking .vimrc"
ln -sf "$HOME/.config/.vimrc" "$HOME/.vimrc"
echo "Linking ipython conf"
ln -sf "$HOME/.config/jupyter/jupyter_notebook_config.py" "$HOME/.jupyter/jupyter_notebook_config.py"
ln -sf "$HOME/.config/jupyter/jupyter_notebook_config.json" "$HOME/.jupyter/jupyter_notebook_config.json"
ln -sf "$HOME/.config/jupyter/templates" "$HOME/data/templates"

echo "pycharm vim"
ln -sf "$HOME/.config/.vimrc" "$HOME/.ideavimrc"

echo "setup labbook"
ln -sf "$HOME/labbook/docs/mkdocs.yml" "$HOME/labbook/"
ln -sf "$HOME/life/docs/Work/tvs.md" "$HOME/labbook/docs/"

echo "tmux conf"
ln -sf "$HOME/.config/tmux/.tmux.conf" "$HOME/"

echo "Add script path to PATH"
export PATH=$PATH:~/bin

echo "get my repos"
cd $HOME/tools && git pull --rebase --autostash

BREW_PACKAGES=(
        "aspell" 
        "ctags"
        "fzf"
        "htop" 
        "postgres"
		"pyenv"
        "shellcheck"
        "the_silver_searcher"
		"tldr"
        "tmux" 
		"tree"
)

BREW_CASKS=(
        "alfred"
        "dash"
        "things3"
		"spotify"
        "virtualbox"
)

PYTHON_REQUIREMENTS=(
                     "autopep8"
					 "black"
					 "csvkit"
					 "flake8"
					 "ipython"
					 "matplotlib"
					 "mypy"
					 "neovim"
					 "requests"
					 "ipdb"
				     "pandas"
                     "jupyter"
                     "mkdocs"
                     "mkdocs-material"
                     "pymdown-extensions"
)

global_pip () {
	echo "update pip"
	pip install --upgrade pip
	for p in "${PYTHON_REQUIREMENTS[@]}"; do
		echo "pip installing $p"
		pip install "$p"
	done
}

if [[ $OSTYPE =~ "darwin" ]]; then
		# check homebrew is installed
		command -v brew >/dev/null 2>&1 || { echo >&2 "Installing Homebrew Now"; \
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; }
        for package in "${BREW_PACKAGES[@]}"; do
                if brew ls --versions $package > /dev/null; then
                        echo "$package is installed"
                else
                        echo "installing $package"
                        brew install $package
                fi
        done
		global_pip

elif [[ $OSTYPE =~ "linux-gnu" ]]; then
        echo "install relevant linux shiz"
		global_pip
fi

echo "Add script path to PATH"
export PATH=$PATH:~/bin

echo "Useful scripts"
cd $HOME/tools/c && make all
find $HOME/tools/c -type f -not \( -name \*.c -or -name Makefile \) -exec ln -sf \{\} "$HOME/bin" \;

for file in $HOME/tools/python/*; do
        ln -sf "$file" "$HOME/bin"
done;

for file in $HOME/tools/bash/*; do
        ln -sf "$file" "$HOME/bin"
done;

# update aspell dictionary
echo "updating spell check"
updatespellcheck

# make sure vim is up to date
nvim --headless +PlugInstall +qall
